### ISSUE TITLE
Error trying to clean  and build CSharp_MARC

### ISSUE THREAD

**Issue by sedj601** [afrozenpeach/CSharp_MARC#14]
I get the error below when I try to clean and building the CSharp_MARC library project.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7027	Error signing output with public key from file 'CSharp_MARC.snk' -- File not found.	CSharp_MARC	C:\Users\theUser\Source\Repos\CSharp_MARC\CSharp_MARC\CSC	1	Active
```

**Comment by afrozenpeach** [comment]
In the project properties go to the security tab and uncheck the sign assembly and sign clickonce options. That should let you build it without needing the signing key.
