### ISSUE TITLE
Record not importing properly

### ISSUE THREAD

**Issue by sedj601** [afrozenpeach/CSharp_MARC#15]
Could you add the attached record to your test case for future releases? I could not get this record to import propertly in your CShapMarcEditor program or while using the FileMarc APIs.

[test.txt](https://github.com/afrozenpeach/CSharp_MARC/files/2886423/test.txt)
[testmarc.txt](https://github.com/afrozenpeach/CSharp_MARC/files/2886431/testmarc.txt)

**Comment by afrozenpeach** [comment]
Sorry for the VERY late reply. I ran testmarc.txt through my library and found no errors.

However, test.txt is not a valid marc21 file and my library will not be able to import that record.

**Comment by sedj601** [comment]
Thanks for the reply. I have determined that my issue is with getting the MARC records from Voyager using the two DLLs that are recommended. Your program is not causing the issue. Sorry!
